version: '3'
services:
  database:
    image: "postgres"
    env_file:
      - .env
    ports:
      - "5432:5432"
    volumes:
      - java-rest-demo:/var/lib/postgresql/data/


volumes:
  java-rest-demo: